from exception_test import convert, convert2, string_logs

# print(convert("55"))
# print(convert("test"))
# print(convert2("55"))
# ValueError
# print(convert2("test"))
# TypeError
# print(convert2([1, 2, 3]))
#raise
# print(string_logs("25"))
print(string_logs("test"))